### ISSUE TITLE
QuantRa-Gui not working

### ISSUE THREAD

**Issue by BJ1GH** [quantum-sp8de/quantra-installer#2]
script runs tkagent without arguments and app is not happy

![image](https://github.com/user-attachments/assets/1c287701-7e9c-46f4-a33b-8855d60c4671)

I'm guessing there needs to be another import for QCICADA_DEVICE

![image](https://github.com/user-attachments/assets/79c99003-3148-47f4-aef7-1571cbc3dac0)

**Comment by plageat** [comment]
Fixed in 4b2691c3978e6ff30f9de3dd1c1bf3e21038e7bc
