### ISSUE TITLE
Each generator should have it's own log

### ISSUE THREAD

**Issue by BJ1GH** [quantum-sp8de/quantra-installer#3]
When multiple generators run simultaneously on one computer system they all use same quantra.log to save debug and info. When log file gets too big, new one is created. Since generators are not synced they detect file too long differently and thus generate each it's own log file.

![image](https://github.com/user-attachments/assets/3bb57100-bda2-4ac3-be43-8c0628791aef)

quantra.log has info from both generators, quantra.log.1 continues with logs for generator on USB0 and quantra.log.2 continues with logs for generator on USB1

suggesting it would be most appropriate if each generator would create and maintain it's own log file(s) either under device or account name

**Comment by plageat** [comment]
The new logging file will be based on device name, for example:

`ttyUSB0_quantra.log`

**Comment by plageat** [comment]
Fixed in 4b2691c3978e6ff30f9de3dd1c1bf3e21038e7bc

**Comment by BJ1GH** [comment]
figured later (during debug) QuantRa has logdir switch so one could create quantra.log in different directories (instead of several files in same directory) like:

quantra -r qcicada -d /dev/ttyUSB0 -c .quantra/quantraUSB0.yaml -l .quantra/USB0/

so this was more like doc issue, not so much application one
