### ISSUE TITLE
QRNG device producing empty input should be warning only

### ISSUE THREAD

**Issue by BJ1GH** [quantum-sp8de/quantra-installer#5]
![image](https://github.com/user-attachments/assets/f21b5f77-d653-411d-a1af-cf92cda2bb63)

if it happens that device produces empty output QuantRa should retry three times every 5 seconds (or any other interval deemed proper) as device recalibrates and returns to normal operation afterwards

**Comment by BJ1GH** [comment]
main.py

![image](https://github.com/user-attachments/assets/6ce95191-fa20-4278-9e6f-718e52ec4b83)

simplest way is to comment line marked

more elaborate way would be to rewrite:

![image](https://github.com/user-attachments/assets/f1d69f59-6b80-435d-8b0f-6f0e679b500d)

in a way it pauses for predefined time (ie 5s) every three consecutive failed attempts and never exits while allways writing number of failed attempt (=retries) together with log message

counter resets as now when first successful push attemp and is not limited - or maybe limited if a day goes by without any push when it exits

would be interesting for generators and validators (if runing on remote site) to send email to owner when failing for like half an hour (like with crypto miners when going offline)

**Comment by BJ1GH** [comment]
if (retries >=3) and ((retries % 3) == 0):
            log.error("Program failed to fix broken state, pausing at '%s'" % retries)
            time.sleep(5)
        elif (retries >= 50000):
            log.error("Program failed to fix broken state, aborting at '%s'" % retries)
            sys.exit(1)

**Comment by plageat** [comment]
We will test QCicada device under the load regarding empty output error to adjust this.

In case you have any log, when after occasional:
`QCicada generated empty output!`
you see repaired normal flow, like^
`"Successfully pushed action with random value: ...`

please share such log here.

**Comment by BJ1GH** [comment]
![image](https://github.com/user-attachments/assets/3e01bf7b-f5b6-4f30-b52a-cd31d45b85b1)

52 fails (empty output cycles) during 7:48:47 and 9:04:54 today longest being apx 1 min
over 11 mins out of 76 were used for device recalibration (as I was told when changes in working environment occur that might affect output device goes into recalibration mode and adjusts before returning any output)

it is not load but most likely temperature variations (when I open window in the morning and cold air gets in the room) that cause empty output

**Comment by BJ1GH** [comment]
![image](https://github.com/user-attachments/assets/bbaede0c-bab8-4834-a284-f51da41b655e)

log example

**Comment by plageat** [comment]
Fixed in dba13d30c6f73a3e72

Now it will just continue the application forever if such error occurs, gradually increasing wait time up to max 5 min until next attempt.

> would be interesting for generators and validators (if runing on remote site) to send email to owner when failing for like half an hour (like with crypto miners when going offline)

As for now it overcomplicates **quantra** application. Perhaps, we can return to the question again at some future point
