### ISSUE TITLE
Generator should have password avail also as argument to anable autorestart after power breakdown or computer restart

### ISSUE THREAD

**Issue by BJ1GH** [quantum-sp8de/quantra-installer#6]
saving pwd in log file is not a good idea too - should have option to exclude or encrypt in some way

**Comment by plageat** [comment]
> saving pwd in log file is not a good idea too

Good catch,  though it barely related to the title of the issue

**Comment by plageat** [comment]
Topic issue fixed in https://github.com/quantum-sp8de/quantra-installer/commit/c454aca463e362c94527c589b22d131d5ee62e77

You can use now **QUANTRA_APP_PSW** environment variable to set quantra password, for example:
```
export QUANTRA_APP_PSW=mypassword
quantra -d /dev/ttyUSB0
```

**Comment by BJ1GH** [comment]
is that valid for all generators (2+) running on the system? what if they have different pwds? not that it is the case but just asking

yeah, looks like valid for single terminal only

**Comment by plageat** [comment]
> is that valid for all generators (2+) running on the system? what if they have different pwds? not that it is the case but just asking
> 
> yeah, looks like valid for single terminal only

All rules using environments variables are applicable. For example, run 2 quantra processes with dedicated passwords each:

```
QUANTRA_APP_PSW=mypassword quantra -d /dev/ttyUSB0
QUANTRA_APP_PSW=mysecondpassword quantra -d /dev/ttyUSB1
```
