### ISSUE TITLE
Autoswitch to another validator node if dedicated one fails

### ISSUE THREAD

**Issue by BJ1GH** [quantum-sp8de/quantra-installer#7]
atm 37.187.144.240 10 nodes don't provide service while 144.217.255.109 11 nodes are running
Generators connected to noperforming nodes failed and are not switching to another avail node same way as validators are
would it be nice if they have access to list of performing nodes and connect to one of performing nodes

**Comment by BJ1GH** [comment]
> Fixed in [dba13d3](https://github.com/quantum-sp8de/quantra-installer/commit/dba13d30c6f73a3e729256d5597e97319f9cae82)
> 
> Now it will just continue the application forever if such error occurs, gradually increasing wait time up to max 5 min until next attempt.
> 
> > would be interesting for generators and validators (if runing on remote site) to send email to owner when failing for like half an hour (like with crypto miners when going offline)
> 
> As for now it overcomplicates **quantra** application. Perhaps, we can return to the question again at some future point

![image](https://github.com/user-attachments/assets/bfdc648e-cb0b-41d2-9bf4-de0be29ff6ba)

if network not operational like now running 13 producers only one can't start Generator as it fails
would be much better to start the app and issue warnings (shorter version) until network recovers and they are able to push randoms to network

**Comment by plageat** [comment]
Currently there are no planes to introduce such feature for the issue topic. Probably, we can do it at some future point later
As a workaround for now, consider using external manually created shell script for implementing such logic
